[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "eolabtools"
description = "Collection of tools for data"
version = "0.0.0"
requires-python = ">=3.8.13"
dependencies = []
readme = "README.md"
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Image Processing",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
homepage = "https://github.com/CNES/eolabtools"
repository = "https://github.com/CNES/eolabtools"

[project.scripts]
night_osm_image_registration = "eolabtools.night_osm_registration.register_image:main"
night_osm_vector_registration = "eolabtools.night_osm_registration.register_vector:main"
